apiVersion: template.openshift.io/v1
kind: Template
labels:
  redis: master
metadata:
  annotations:
    description: Description
    tags: ceph
  name: ceph-template
objects:
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: ${PROJECT_NAME}-ceph-cluster-admin
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
  subjects:
  - kind: ServiceAccount
    name: ceph-internal-cluster-admin
    namespace: ${PROJECT_NAME}
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ceph-internal-cluster-admin
parameters:
- description: Project where CephCluster will be deployed
  value: ceph
  name: PROJECT_NAME
