apiVersion: template.openshift.io/v1
kind: Template
labels:
  redis: master
metadata:
  annotations:
    description: Description
    tags: ceph
  creationTimestamp: null
  name: ceph-object-store-template
- apiVersion: ceph.rook.io/v1
  kind: CephObjectStore
  metadata:
    name: my-store
  spec:
    metadataPool:
      replicated:
        size: 1
    dataPool:
      replicated:
        size: 1
    gateway:
      type: s3
      port: 8080
      securePort:
      instances: 1
- apiVersion: ceph.rook.io/v1
  kind: CephObjectStoreUser
  metadata:
    name: my-user
  spec:
    store: my-store
    displayName: "my display name"
parameters: